services:
  api:
    build:
      context: .
      target: gin-dev
    ports:
      - "2345:2345"
      - "8080:8080"
    volumes:
      - .:/app
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
  web:
    build:
      target: web-dev
    ports:
      - "5173:5173"
    restart: unless-stopped